### ISSUE TITLE
bootstrap.sh password authentication failed for user 

### ISSUE THREAD

**Issue by webmasteraxe** [heroku/mobile-template1#29]
unable to run the command bootstrap.sh from my git bash , giving the following error

error: password authentication failed for user "amungara"
    at Connection.parseE (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:534:11)
    at Connection.parseMessage (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:361:17)
    at Socket.<anonymous> (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
Possibly unhandled error: password authentication failed for user "amungara"
    at Connection.parseE (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:534:11)
    at Connection.parseMessage (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:361:17)
    at Socket.<anonymous> (c:\Users\amungara\RotoRooter\mobile-template\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)

**Comment by webmasteraxe** [comment]
after configuring my git credentials.....still im getting this error..

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
Possibly unhandled Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
