### ISSUE TITLE
Deploy fails on no-modified template

### ISSUE THREAD

**Issue by davidedc97** [heroku/mobile-template1#30]
Just forked the repo, no modifications, and when I try to deploy the app on heroku (through the button) it throws me errors. I tried with and without pipeline, same error on build. Here's the log from the "Build app" console :

-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  0.10.35
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 0.10.35...
       Downloading and installing node 0.10.35...
       Using default npm version: 1.4.28
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > bcrypt@0.8.7 install /tmp/build_5678070d_/node_modules/bcrypt
       > node-gyp rebuild
       
       make: Entering directory '/tmp/build_5678070d_/node_modules/bcrypt/build'
         CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
         CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
         CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
         SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
         SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
         COPY Release/bcrypt_lib.node
       make: Leaving directory '/tmp/build_5678070d_/node_modules/bcrypt/build'
       
       > pg@3.6.4 install /tmp/build_5678070d_/node_modules/pg
       > node-gyp rebuild || (exit 0)
       
       make: Entering directory '/tmp/build_5678070d_/node_modules/pg/build'
         CXX(target) Release/obj.target/binding/src/binding.o
         SOLINK_MODULE(target) Release/obj.target/binding.node
         SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
         COPY Release/binding.node
       make: Leaving directory '/tmp/build_5678070d_/node_modules/pg/build'
       
       > utf-8-validate@5.0.3 install /tmp/build_5678070d_/node_modules/websocket/node_modules/utf-8-validate
       > node-gyp-build
       
       make: Entering directory '/tmp/build_5678070d_/node_modules/websocket/node_modules/utf-8-validate/build'
         CC(target) Release/obj.target/validation/src/validation.o
       ../src/validation.c:3:10: fatal error: node_api.h: No such file or directory
        #include <node_api.h>
                 ^~~~~~~~~~~~
       compilation terminated.
       validation.target.mk:85: recipe for target 'Release/obj.target/validation/src/validation.o' failed
       make: *** [Release/obj.target/validation/src/validation.o] Error 1
       make: Leaving directory '/tmp/build_5678070d_/node_modules/websocket/node_modules/utf-8-validate/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_5678070d_/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
       gyp ERR! System Linux 4.4.0-1081-aws
       gyp ERR! command "node" "/tmp/build_5678070d_/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_5678070d_/node_modules/websocket/node_modules/utf-8-validate
       gyp ERR! node -v v0.10.35
       gyp ERR! node-gyp -v v1.0.1
       gyp ERR! not ok 
       
       > bufferutil@4.0.2 install /tmp/build_5678070d_/node_modules/websocket/node_modules/bufferutil
       > node-gyp-build
       
       make: Entering directory '/tmp/build_5678070d_/node_modules/websocket/node_modules/bufferutil/build'
         CC(target) Release/obj.target/bufferutil/src/bufferutil.o
       ../src/bufferutil.c:3:10: fatal error: node_api.h: No such file or directory
        #include <node_api.h>
                 ^~~~~~~~~~~~
       compilation terminated.
       bufferutil.target.mk:85: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
       make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
       make: Leaving directory '/tmp/build_5678070d_/node_modules/websocket/node_modules/bufferutil/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_5678070d_/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
       gyp ERR! System Linux 4.4.0-1081-aws
       gyp ERR! command "node" "/tmp/build_5678070d_/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_5678070d_/node_modules/websocket/node_modules/bufferutil
       gyp ERR! node -v v0.10.35
       gyp ERR! node-gyp -v v1.0.1
       gyp ERR! not ok 
       
       > sqlite3@3.1.13 install /tmp/build_5678070d_/node_modules/sqlite3
       > node-pre-gyp install --fallback-to-build
       
       [sqlite3] Success: "/tmp/build_5678070d_/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" is installed via remote
       npm ERR! utf-8-validate@5.0.3 install: `node-gyp-build`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the utf-8-validate@5.0.3 install script.
       npm ERR! This is most likely a problem with the utf-8-validate package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp-build
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls utf-8-validate
       npm ERR! There is likely additional logging output above.
       
       npm ERR! System Linux 4.4.0-1081-aws
       npm ERR! command "/tmp/build_5678070d_/.heroku/node/bin/node" "/tmp/build_5678070d_/.heroku/node/bin/npm" "install" "--production=false" "--unsafe-perm" "--userconfig" "/tmp/build_5678070d_/.npmrc"
       npm ERR! cwd /tmp/build_5678070d_
       npm ERR! node -v v0.10.35
       npm ERR! npm -v 1.4.28
       npm ERR! code ELIFECYCLE
       npm ERR! not ok code 0
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - This version of npm (1.4.28) has several known issues - consider upgrading to the latest release (6.14.9)
         https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by scottpersinger** [comment]
This project is super old, so I'm sure there's been enough Node package churn to result in this error. Someone needs to update all the dependent packages by hand to their latest versions and make sure everything still runs. That someone is not likely to be me any time soon, but maybe at some point...
